# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: SSHA


  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    app_users:
      ldap:
        service: app.ldap
        base_dn: ou=people,dc=airfrance,dc=fr
        search_dn: cn=yourCN,ou=profile,dc=airfrance,dc=fr
        search_password: password
        filter: uid={username}
        default_roles: ROLE_USER


    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern:   ^/
      anonymous: true
      provider:  app_users
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:   logout
        target: /platform



  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
